\ Null personality - disables console output
create null-personality
  4 cells , 19 , 0 , 0 ,
  ' noop , \ INVOKE    ( -- )
  ' noop , \ REVOKE    ( -- )
  ' noop , \ /INPUT    ( -- )
  ' drop ,  \ EMIT      ( char -- )
  ' 2drop , \ TYPE      ( addr len -- )
  ' 2drop , \ ?TYPE     ( addr len -- )
  ' noop , \ CR        ( -- )
  ' noop , \ PAGE      ( -- )
  ' drop , \ ATTRIBUTE ( n -- )
  ' dup , \ KEY       ( -- char )
  ' dup , \ KEY?      ( -- flag )
  ' dup , \ EKEY      ( -- echar )
  ' dup , \ EKEY?     ( -- flag )
  ' dup , \ AKEY      ( -- char )
  ' 2drop , \ PUSHTEXT  ( addr len -- )
  ' 2drop ,  \ AT-XY     ( x y -- )
  ' 2dup , \ GET-XY    ( -- x y )
  ' 2dup , \ GET-SIZE  ( -- x y )
  ' drop , \ ACCEPT    ( addr u1 -- u2)
